[tapo]
ip=192.168.0.XXX

[tapo.highres]
stream_path=stream1

[tapo.lowres]
stream_path=stream2

[axis]
ip=192.168.0.XXX
stream_path=axis-media/media.amp
port=554

[reolink]
ip=192.168.1.XXX

[reolink.highres]
stream_path=h264Preview_01_main

[reolink.H265]
stream_path=h265Preview_01_main

[reolink.lowres]
stream_path=h264Preview_01_sub